# Generated by Django 3.2 on 2021-09-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('max_amount_of_trucks', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account_app.accountcategory'),
        ),
    ]
