# Generated by Django 3.2 on 2021-09-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0003_auto_20210927_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_untill',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
