# Generated by Django 3.2 on 2021-09-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0005_alter_user_paid_untill'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='dot_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='mc_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ocupation',
            field=models.CharField(choices=[('COMPANY OWNER', 'COMPANY OWNER'), ('FLEET MANAGER', 'FLOAT MANAGER'), ('DRIVER', 'DRIVER')], default='COMPANY OWNER', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='usa_state',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='', max_length=256),
        ),
    ]
