# Generated by Django 3.2 on 2021-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='password',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
