# Generated by Django 3.2 on 2021-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0008_driverprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='first_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='last_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
