# Generated by Django 3.2 on 2021-10-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0010_auto_20211003_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='email',
            new_name='driver_email',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='phone',
            new_name='driver_phone',
        ),
    ]
