# Generated by Django 3.2 on 2021-10-03 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_management_app', '0003_alter_truck_driver'),
        ('user_account_app', '0011_auto_20211003_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountcategory',
            name='max_amount_of_drivers',
        ),
        migrations.AddField(
            model_name='user',
            name='dot_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='mc_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('COMPANY OWNER', 'COMPANY OWNER'), ('FLEET MANAGER', 'FLOAT MANAGER'), ('DRIVER', 'DRIVER')], default='COMPANY OWNER', max_length=256),
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
