# Generated by Django 3.2 on 2022-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0012_auto_20211003_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('COMPANY OWNER', 'COMPANY OWNER'), ('FLEET MANAGER', 'FLEET MANAGER'), ('DRIVER', 'DRIVER')], default='COMPANY OWNER', max_length=256),
        ),
    ]
