# Generated by Django 3.2 on 2022-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0015_auto_20220208_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='ocupation',
            field=models.CharField(choices=[('COMPANY OWNER', 'COMPANY OWNER'), ('DRIVER', 'DRIVER')], default='DRIVER', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('COMPANY OWNER', 'COMPANY OWNER'), ('DRIVER', 'DRIVER')], default='COMPANY OWNER', max_length=256),
        ),
    ]
