# Generated by Django 3.2 on 2022-02-22 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0016_auto_20220218_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('TAKEN', 'TAKEN'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], default='AVAILABLE', max_length=256)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account_app.driver')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
