# Generated by Django 3.2 on 2022-05-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0017_offerjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paid_untill',
            new_name='paid_until',
        ),
    ]
