# Generated by Django 3.2 on 2021-09-27 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0005_alter_user_paid_untill'),
        ('truck_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statetaxes',
            options={'verbose_name_plural': 'state taxes'},
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account_app.driverprofile'),
        ),
    ]
