# Generated by Django 3.2 on 2022-02-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck_management_app', '0003_alter_truck_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='driver',
            new_name='owner',
        ),
    ]
