# Generated by Django 3.2 on 2022-02-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0014_auto_20220207_1653'),
        ('truck_management_app', '0004_rename_driver_truck_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account_app.driver'),
        ),
    ]
