# Generated by Django 3.2 on 2022-02-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0016_auto_20220218_0019'),
        ('truck_management_app', '0005_truck_current_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarter',
            old_name='total_non_toll_milles',
            new_name='total_non_toll_miles',
        ),
        migrations.RenameField(
            model_name='quarter',
            old_name='total_toll_milles',
            new_name='total_toll_miles',
        ),
        migrations.RenameField(
            model_name='statereport',
            old_name='total_non_toll_milles',
            new_name='total_non_toll_miles',
        ),
        migrations.RenameField(
            model_name='statereport',
            old_name='total_toll_milles',
            new_name='total_toll_miles',
        ),
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('total_toll_miles', models.FloatField(default=0.0)),
                ('total_non_toll_miles', models.FloatField(default=0.0)),
                ('total_gallons', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('usa_state', models.CharField(default='-1', max_length=256)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account_app.driver')),
                ('truck', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck_management_app.truck')),
            ],
        ),
    ]
