# Generated by Django 3.2 on 2022-02-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_management_app', '0006_auto_20220218_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='current_quarter',
            field=models.IntegerField(default=1),
        ),
    ]
